### ISSUE TITLE
creating my own onnx file to use with pico-cnn

### ISSUE THREAD

**Issue by amamory** [ekut-es/pico-cnn#3]
I am trying to create my own small cnn just to test the flow from tf.keras to C using pico-cnn.

My first step was to use the latest version of tf.keras (2.2.0) and onnx (1.7.0), but them I get this error when running python3.6 onnx_to_pico_cnn.py.

```
Generating Pico-CNN Code for model: mnist-model
Traceback (most recent call last):
  File "onnx_to_pico_cnn.py", line 72, in <module>
    main()
  File "onnx_to_pico_cnn.py", line 66, in main
    onnx_to_pico_cnn(onnx_model, model_name)
  File "onnx_to_pico_cnn.py", line 31, in onnx_to_pico_cnn
    onnx.checker.check_model(onnx_model)
  File "/home/lsa/.local/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.
```

The flow to generate the onnx file is in this [notebook](https://colab.research.google.com/drive/1-Zi8bd9Hyi80ReeUBWfXh99LJEMml5U9?usp=sharing).

Then, i was trying to downgrade both tf.keras and onnx, to match the versions used in pico-cnn.
So, I built this [notebook](https://colab.research.google.com/drive/1hErRPNY4pB2KvvNple_1g0g_NcB0A8e1?usp=sharing) where i am using the same versions of tf and onnx you are using in pico-cnn.

I tried this conversion with and without TF's eager mode enabled, but in both cases I got errors 

**ERROR with eager mode off:**

```
keras2onnx version is 1.5.0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras2onnx/common/utils.py:38: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras2onnx/common/utils.py:38: The name tf.logging.WARN is deprecated. Please use tf.compat.v1.logging.WARN instead.

Using TensorFlow backend.

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-21-d58d6c50760c> in <module>()
      2 print("keras2onnx version is "+keras2onnx.__version__)
      3 # convert to onnx model
----> 4 onnx_model = keras2onnx.convert_keras(model, 'mnist-onnx', debug_mode=1)
      5 output_model_path = "/content/drive/My Drive/Colab Notebooks/models/mnist-model.onnx"
      6 # and save the model in ONNX format

3 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in __iter__(self)
    475     if not context.executing_eagerly():
    476       raise TypeError(
--> 477           "Tensor objects are only iterable when eager execution is "
    478           "enabled. To iterate over this tensor use tf.map_fn.")
    479     shape = self._shape_tuple()

TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
```

**ERROR with eager mode on:**

```
keras2onnx version is 1.5.0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras2onnx/common/utils.py:38: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras2onnx/common/utils.py:38: The name tf.logging.WARN is deprecated. Please use tf.compat.v1.logging.WARN instead.

Using TensorFlow backend.

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-12-d58d6c50760c> in <module>()
      2 print("keras2onnx version is "+keras2onnx.__version__)
      3 # convert to onnx model
----> 4 onnx_model = keras2onnx.convert_keras(model, 'mnist-onnx', debug_mode=1)
      5 output_model_path = "/content/drive/My Drive/Colab Notebooks/models/mnist-model.onnx"
      6 # and save the model in ONNX format

1 frames

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in get_session()
    381     if tf.executing_eagerly():
    382         raise RuntimeError(
--> 383             '`get_session` is not available when '
    384             'TensorFlow is executing eagerly.')
    385     return tf_keras_backend.get_session()

RuntimeError: `get_session` is not available when TensorFlow is executing eagerly.
```

questions:
1) have you ever tried something similar to this ? if yes, how is your flow ?
2) I am using tf-keras, would you suggest another flow ?
3) is there any plan to update pico-cnn to newer onnx and tf versions ?
4) any other kind of help ?

thanks !
Alexandre

**Comment by alexjung** [comment]
Hello Alexandre,

thanks for your interest in Pico-CNN. I will try to answer your questions as best as possible:
1.+2. So far we have mainly worked with pre-trained onnx models from the [onnx model zoo](https://github.com/onnx/models). But when we did our own training it was mostly done in PyTorch. An example I have created on MNIST can be found [here](https://github.com/alexjung/ParalleNet).
3. Yes there is. We are currently working on the next release where we would also like to update the dependencies of the project.
4. As mentioned above you can check out the MNIST example on my private GitHub page.

Best regards
Alexander

**Comment by amamory** [comment]
Thanks Alexander,

Meanwhile I will try the PyTorch-based flow and I will let you know of the results.

regards,
Alexandre
